<a href="https://colab.research.google.com/github/j-atin/Deep-Learning/blob/main/AI2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [7]:
df = pd.read_csv('insurance_data.csv')

In [9]:
df.head()

age  affordibility  bought_insurance
0   22              1                 0
1   25              0                 0
2   47              1                 1
3   52              0                 0
4   46              1                 1

In [10]:
pip install sci-kit learn

  Preparing metadata (setup.py) ... done
  Created wheel for learn: filename=learn-1.0.0-py3-none-any.whl size=1232 sha256=2373d8a9ddcca702dfe1f9ddb0d0d070e17d963b0a0e1a695593fab1f87c8cb7
  Stored in directory: /root/.cache/pip/wheels/07/46/4f/59633ae06635ca5d36a42e6c3a2043bf1e4cdd351e6dbb39aa
Successfully built learn


In [24]:
from sklearn.model_selection import train_test_split
X_train , X_test, y_train, y_test = train_test_split(df[['age','affordibility']],
                                                           df.bought_insurance, test_size=0.2, random_state=25)

In [25]:
X_train_scaled = X_train.copy()
X_train_scaled['age'] = X_train_scaled['age']/100

X_test_scaled = X_test.copy()
X_test_scaled['age'] = X_test_scaled['age']/100

In [37]:
model = keras.Sequential([
  keras.layers.Dense(1,input_shape=(2,),activation = 'sigmoid',
  kernel_initializer='ones',bias_initializer='zeros'),
  keras.layers.Dense(1,input_shape=(2,),activation = 'relu',
  kernel_initializer='ones',bias_initializer='zeros')
])

model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
model.fit(X_train_scaled,y_train,epochs=1000)

Epoch 1/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 983ms/step - accuracy: 0.5000 - loss: 0.7113
Epoch 2/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.5000 - loss: 0.7092
Epoch 3/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5000 - loss: 0.7072
Epoch 4/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.5000 - loss: 0.7051
Epoch 5/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.5000 - loss: 0.7031
Epoch 6/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.5000 - loss: 0.7012
Epoch 7/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.5000 - loss: 0.6992
Epoch 8/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.5000 - loss: 0.6973
Epoch 9/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.5000 - loss: 0.6954
Epoch 10/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.5000 - loss: 0.6936
Epoch 11/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.5000 - loss: 0.6918
Epoch 12/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy

In [27]:
model.evaluate(X_test_scaled,y_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 198ms/step - accuracy: 0.6667 - loss: 0.5855


[0.5854937434196472, 0.6666666865348816]

In [28]:
model.predict(X_test_scaled)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 137ms/step


array([[0.6447141 ],
       [0.56694895],
       [0.40433905],
       [0.5943529 ],
       [0.6498545 ],
       [0.6799389 ]], dtype=float32)

In [29]:
y_test

2     1
10    0
21    0
11    0
14    1
9     1
Name: bought_insurance, dtype: int64

In [30]:
coef , intercept = model.get_weights()

In [32]:
coef, intercept

(array([[1.1257617 ],
        [0.74689245]], dtype=float32),
 array([-0.68011606], dtype=float32))